export const SAMPLE_DATASETS = {
  exoplanets: {
    name: "James Webb Exoplanet Habitability Catalog",
    description: "Astrophysical measurements of confirmed exoplanets, stellar distance, surface temperatures, and Earth Similarity Index (ESI).",
    data: [
      { Planet: "Proxima Centauri b", Distance_Light_Years: 4.25, Mass_Earths: 1.17, Orbital_Days: 11.2, Temp_Kelvin: 234, Earth_Similarity_Pct: 87 },
      { Planet: "TRAPPIST-1e", Distance_Light_Years: 39.46, Mass_Earths: 0.69, Orbital_Days: 6.1, Temp_Kelvin: 251, Earth_Similarity_Pct: 95 },
      { Planet: "TRAPPIST-1f", Distance_Light_Years: 39.46, Mass_Earths: 1.04, Orbital_Days: 9.2, Temp_Kelvin: 219, Earth_Similarity_Pct: 90 },
      { Planet: "Kepler-452b", Distance_Light_Years: 1402, Mass_Earths: 5.0, Orbital_Days: 384.8, Temp_Kelvin: 265, Earth_Similarity_Pct: 83 },
      { Planet: "Kepler-186f", Distance_Light_Years: 582, Mass_Earths: 1.4, Orbital_Days: 129.9, Temp_Kelvin: 188, Earth_Similarity_Pct: 77 },
      { Planet: "LHS 1140 b", Distance_Light_Years: 48.8, Mass_Earths: 6.98, Orbital_Days: 24.7, Temp_Kelvin: 235, Earth_Similarity_Pct: 84 },
      { Planet: "Gliese 667 Cc", Distance_Light_Years: 23.6, Mass_Earths: 3.8, Orbital_Days: 28.1, Temp_Kelvin: 277, Earth_Similarity_Pct: 85 },
      { Planet: "K2-18b", Distance_Light_Years: 124, Mass_Earths: 8.63, Orbital_Days: 32.9, Temp_Kelvin: 255, Earth_Similarity_Pct: 73 },
      { Planet: "TOI-700 d", Distance_Light_Years: 101.4, Mass_Earths: 1.72, Orbital_Days: 37.4, Temp_Kelvin: 269, Earth_Similarity_Pct: 93 },
    ],
    defaultX: "Planet",
    defaultY: "Earth_Similarity_Pct",
  },
  genomics: {
    name: "CRISPR-Cas9 Gene Editing Efficiency",
    description: "Molecular genetics laboratory data tracking gene cleavage precision, on-target success rates, and cellular viability.",
    data: [
      { Target_Gene: "BRCA1", On_Target_Pct: 94.2, Off_Target_Mutations: 2, Cleavage_Efficiency: 91.5, Cell_Viability_Pct: 89.4 },
      { Target_Gene: "TP53", On_Target_Pct: 88.7, Off_Target_Mutations: 6, Cleavage_Efficiency: 86.0, Cell_Viability_Pct: 82.1 },
      { Target_Gene: "CFTR", On_Target_Pct: 96.5, Off_Target_Mutations: 1, Cleavage_Efficiency: 95.3, Cell_Viability_Pct: 94.0 },
      { Target_Gene: "HBB (Sickle Cell)", On_Target_Pct: 97.8, Off_Target_Mutations: 1, Cleavage_Efficiency: 96.2, Cell_Viability_Pct: 92.8 },
      { Target_Gene: "DMD (Dystrophin)", On_Target_Pct: 82.4, Off_Target_Mutations: 8, Cleavage_Efficiency: 79.1, Cell_Viability_Pct: 78.5 },
      { Target_Gene: "PCSK9", On_Target_Pct: 95.1, Off_Target_Mutations: 3, Cleavage_Efficiency: 93.8, Cell_Viability_Pct: 91.0 },
      { Target_Gene: "CCR5", On_Target_Pct: 98.4, Off_Target_Mutations: 0, Cleavage_Efficiency: 97.6, Cell_Viability_Pct: 96.2 },
    ],
    defaultX: "Target_Gene",
    defaultY: "On_Target_Pct",
  },
  ocean: {
    name: "Abyssal Hydrothermal Vent Ecology",
    description: "Deep-sea oceanographic sensor metrics measuring extremophile biodiversity, temperature gradients, and methane concentrations.",
    data: [
      { Vent_System: "Lost City Field", Depth_Meters: 750, Water_Temp_C: 90, pH_Level: 9.8, Extremophile_Biomass: 1420, Methane_uM: 210 },
      { Vent_System: "TAG Hydrothermal", Depth_Meters: 3650, Water_Temp_C: 360, pH_Level: 3.1, Extremophile_Biomass: 880, Methane_uM: 95 },
      { Vent_System: "Rainbow Field", Depth_Meters: 2300, Water_Temp_C: 365, pH_Level: 2.8, Extremophile_Biomass: 1250, Methane_uM: 320 },
      { Vent_System: "Lucky Strike", Depth_Meters: 1700, Water_Temp_C: 324, pH_Level: 4.2, Extremophile_Biomass: 1680, Methane_uM: 180 },
      { Vent_System: "Snakepit Ridge", Depth_Meters: 3480, Water_Temp_C: 350, pH_Level: 3.5, Extremophile_Biomass: 940, Methane_uM: 140 },
      { Vent_System: "Endeavour Segment", Depth_Meters: 2200, Water_Temp_C: 380, pH_Level: 3.0, Extremophile_Biomass: 1110, Methane_uM: 260 },
    ],
    defaultX: "Vent_System",
    defaultY: "Extremophile_Biomass",
  },
  quantum: {
    name: "CERN Particle Accelerator Collisions",
    description: "High-energy subatomic particle collision measurements, beam luminosity, and Higgs Boson candidate events.",
    data: [
      { Collision_Run: "Run 301 - Proton", Energy_TeV: 13.6, Integrated_Luminosity_pb: 450, Higgs_Decay_Events: 42, Muon_Pairs_Observed: 3120 },
      { Collision_Run: "Run 302 - Heavy Ion", Energy_TeV: 5.36, Integrated_Luminosity_pb: 120, Higgs_Decay_Events: 8, Muon_Pairs_Observed: 980 },
      { Collision_Run: "Run 303 - High Lum", Energy_TeV: 13.6, Integrated_Luminosity_pb: 680, Higgs_Decay_Events: 68, Muon_Pairs_Observed: 4550 },
      { Collision_Run: "Run 304 - Proton", Energy_TeV: 13.6, Integrated_Luminosity_pb: 520, Higgs_Decay_Events: 51, Muon_Pairs_Observed: 3740 },
      { Collision_Run: "Run 305 - Heavy Ion", Energy_TeV: 5.36, Integrated_Luminosity_pb: 210, Higgs_Decay_Events: 14, Muon_Pairs_Observed: 1430 },
      { Collision_Run: "Run 306 - Ultra Beam", Energy_TeV: 14.0, Integrated_Luminosity_pb: 850, Higgs_Decay_Events: 94, Muon_Pairs_Observed: 5890 },
    ],
    defaultX: "Collision_Run",
    defaultY: "Higgs_Decay_Events",
  },
};
